#:import JobItem ci_screen.widgets.job_item.JobItem
#:import Color kivy.graphics.Color


<JobItem>:
    canvas:
        Color:
            rgba: (0,1,0,1) if root.project.succeeded else (1,0,0,1)
        Rectangle:
            pos: self.x + 2, self.y + 2
            size: self.width - 4, self.height - 4
    Label:
        id: label
        pos: root.pos
        size: self.texture_size
        text: root.project.name
        color: 1,1,1,1
